### ISSUE TITLE
Put Handleless Components onto Dev 3 for proofing.

### ISSUE THREAD

**Issue by BAmarketing** [BAmarketing/Going-Live-31st-March#1]
I will email the database with component info

**Comment by fsphil** [comment]
Can you create this issue under myba, you seem to have created a separate project for it.

**Comment by BAmarketing** [comment]
This is my fault Phil.  We thought it might be easier to have a work stream just dedicated to product launch activity for 31st March so that nothing gets missed amongst all the other issues.  It also gives us focus on what we have sent through to date etc.  If this doesn’t work for you, we can revert?  I understand you don’t want lots of work streams to have to check!!
